import { execSync } from "child_process";
import { existsSync, readFileSync, readdirSync, statSync, writeFileSync, rmSync } from "fs";
import { join, extname } from "path";

const REPO_B_URL = "https://github.com/thtrgng/RORU-content-writer-.git";
const CLONE_DIR = join(process.cwd(), "lib/content-system/repo");
const OUTPUT_FILE = join(process.cwd(), "lib/content-system/system-prompt.ts");

const KNOWLEDGE_EXTENSIONS = [".md", ".txt"];
const EXCLUDED_DIRS = [".git", "node_modules", "Posts"];

function collectFiles(dir: string, files: string[] = []): string[] {
  if (!existsSync(dir)) return files;
  for (const entry of readdirSync(dir)) {
    const fullPath = join(dir, entry);
    const stat = statSync(fullPath);
    if (stat.isDirectory()) {
      if (!EXCLUDED_DIRS.includes(entry)) {
        collectFiles(fullPath, files);
      }
    } else if (KNOWLEDGE_EXTENSIONS.includes(extname(entry).toLowerCase())) {
      files.push(fullPath);
    }
  }
  return files;
}

function buildSystemPrompt(repoDir: string): string {
  const files = collectFiles(repoDir);
  if (files.length === 0) {
    console.warn("[sync] No knowledge files found in Repo B");
    return "You are the RORU caption writing assistant.";
  }

  const sections = files.map((filePath) => {
    const relativePath = filePath.replace(repoDir + "/", "");
    const content = readFileSync(filePath, "utf-8").trim();
    return `### ${relativePath}\n\n${content}`;
  });

  console.log(`[sync] Embedded ${files.length} files from Repo B`);
  return sections.join("\n\n---\n\n");
}

function main() {
  const token = process.env.GITHUB_TOKEN;

  // Clone or pull Repo B
  if (existsSync(CLONE_DIR)) {
    rmSync(CLONE_DIR, { recursive: true, force: true });
  }

  const cloneUrl = token
    ? REPO_B_URL.replace("https://", `https://${token}@`)
    : REPO_B_URL;

  console.log("[sync] Cloning Repo B...");
  try {
    execSync(`git clone --depth 1 "${cloneUrl}" "${CLONE_DIR}"`, {
      stdio: "inherit",
    });
  } catch (err) {
    console.error("[sync] Failed to clone Repo B:", err);
    console.warn("[sync] Using stub system prompt");
    return;
  }

  const systemPrompt = buildSystemPrompt(CLONE_DIR);

  const escaped = systemPrompt
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$\{/g, "\\${");

  const output = `// Auto-generated by scripts/sync-content-system.ts — do not edit\nexport const SYSTEM_PROMPT = \`${escaped}\`;\n`;

  writeFileSync(OUTPUT_FILE, output, "utf-8");
  console.log(`[sync] Written to ${OUTPUT_FILE}`);
}

main();
