import { execSync } from "child_process";
import { existsSync, readFileSync, readdirSync, statSync, writeFileSync, rmSync } from "fs";
import { join, extname } from "path";

const REPO_B_URL = "https://github.com/thtrgng/RORU-content-writer-.git";
const CLONE_DIR = join(process.cwd(), "lib/content-system/repo");
const OUTPUT_FILE = join(process.cwd(), "lib/content-system/system-prompt.ts");

const KNOWLEDGE_EXTENSIONS = [".md", ".txt"];
const EXCLUDED_DIRS = [".git", "node_modules", "Posts"];

function collectFiles(dir: string, files: string[] = []): string[] {
  if (!existsSync(dir)) return files;
  for (const entry of readdirSync(dir)) {
    const fullPath = join(dir, entry);
    const stat = statSync(fullPath);
    if (stat.isDirectory()) {
      if (!EXCLUDED_DIRS.includes(entry)) {
        collectFiles(fullPath, files);
      }
    } else if (KNOWLEDGE_EXTENSIONS.includes(extname(entry).toLowerCase())) {
      files.push(fullPath);
    }
  }
  return files;
}

// ~20k tokens worth of characters; leaves headroom for conversation within the 30k/min limit
const SYSTEM_PROMPT_CHAR_LIMIT = 80_000;

function buildSystemPrompt(repoDir: string): string {
  const allFiles = collectFiles(repoDir);
  if (allFiles.length === 0) {
    console.warn("[sync] No knowledge files found in Repo B");
    return "You are the RORU caption writing assistant.";
  }

  // SKILL.md files are the most critical — include them first
  const skillFiles = allFiles.filter((f) =>
    f.toLowerCase().includes("skill")
  );
  const otherFiles = allFiles.filter((f) =>
    !f.toLowerCase().includes("skill")
  );
  const ordered = [...skillFiles, ...otherFiles];

  let total = 0;
  const sections: string[] = [];
  let included = 0;
  let skipped = 0;

  for (const filePath of ordered) {
    const relativePath = filePath.replace(repoDir + "/", "");
    const content = readFileSync(filePath, "utf-8").trim();
    const section = `### ${relativePath}\n\n${content}`;
    if (total + section.length > SYSTEM_PROMPT_CHAR_LIMIT) {
      skipped++;
      continue;
    }
    sections.push(section);
    total += section.length;
    included++;
  }

  console.log(
    `[sync] Embedded ${included} files from Repo B (${skipped} skipped, ${total} chars)`
  );
  return sections.join("\n\n---\n\n");
}

function main() {
  const token = process.env.GITHUB_TOKEN?.trim();

  // Clone or pull Repo B
  if (existsSync(CLONE_DIR)) {
    rmSync(CLONE_DIR, { recursive: true, force: true });
  }

  const cloneUrl = token
    ? REPO_B_URL.replace("https://", `https://${token}@`)
    : REPO_B_URL;

  console.log("[sync] Cloning Repo B...");
  try {
    execSync(`git clone --depth 1 "${cloneUrl}" "${CLONE_DIR}"`, {
      stdio: "inherit",
      env: {
        ...process.env,
        GIT_TERMINAL_PROMPT: "0",
        GIT_ASKPASS: "echo",
      },
    });
  } catch (err) {
    console.error("[sync] Failed to clone Repo B:", err);
    console.warn("[sync] Using stub system prompt");
    return;
  }

  const systemPrompt = buildSystemPrompt(CLONE_DIR);

  const escaped = systemPrompt
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$\{/g, "\\${");

  const output = `// Auto-generated by scripts/sync-content-system.ts — do not edit\nexport const SYSTEM_PROMPT = \`${escaped}\`;\n`;

  writeFileSync(OUTPUT_FILE, output, "utf-8");
  console.log(`[sync] Written to ${OUTPUT_FILE}`);
}

main();
